name: bpb
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=2.7
  - pip
  - pyqt
  - conda-forge::biopython=1.76
  - bioconda::dendropy
  - conda-forge::ete3
  - conda-forge::matplotlib
  - conda-forge::nestly
  - conda-forge::numpy
  - conda-forge::pandas
  - conda-forge::scipy
  - conda-forge::scons
  - conda-forge::seaborn
  - bioconda::seqmagick
  - conda-forge::statsmodels
  - conda-forge::colored-traceback
